import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "@/layouts/Navigation";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "쌍밥",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${roboto.variable} min-h-screen antialiased bg-[#f5f5f5]`}
    >
      <body className="flex flex-col w-full min-h-screen bg-white">
        <main className="flex-1">{children}</main>
        <Navigation />
      </body>
    </html>
  );
}
